### ISSUE TITLE
homographs

### ISSUE THREAD

**Issue by danielrruf** [cltk/greek_lexica_perseus#4]
There's a problem with homographs, isn't it? 

In a different, but connected issue, there is a weird thing:

If you look for 
print (LEMMATA.get("ἐρῶ"))
you get ἐράομαι
but if you look for ἐρῶ (look for the different codepoints for omega with circumflex)
print (LEMMATA.get("ἐρῶ"))
you get ἐρῶ
why?

**Comment by diyclassics** [comment]
Moved to #3
