### ISSUE TITLE
transform_lemmata.py outputs duplicate entries that differ only in normalization

### ISSUE THREAD

**Issue by whoopsedesy** [cltk/greek_lexica_perseus#5]
`parse_perseus_lemmata_file` is a triply nested loop. The inner loop processes each (`headword`, `lemma`) pair multiple times, one time for each part of speech. Each iteration of the inner loop beta-decodes `headword` and `lemma`; however `headword` and `lemma` may already have been beta-decoded in a previous iteration. A side effect of the double decoding seems to be that certain precomposed characters, like GREEK SMALL LETTER IOTA WITH PERISPOMENI, are transformed into a sequence with combining characters, like [GREEK SMALL LETTER IOTA, COMBINING GREEK PERISPOMENI]. The effect on the output is that certain entries in `LEMMATA` are bifurcated, with duplicate keys and values that differ in their Unicode normalization. You can see the effect using this patch:
```diff
diff --git a/transform_lemmata.py b/transform_lemmata.py
index e0b7eb7..fd4221e 100644
--- a/transform_lemmata.py
+++ b/transform_lemmata.py
@@ -4,6 +4,7 @@ from cltk.corpus.greek.beta_to_unicode import Replacer
 from collections import Counter
 from collections import defaultdict
 import operator
+import unicodedata
 
 replacer = Replacer()
 
@@ -53,7 +54,11 @@ def parse_perseus_lemmata_file(file_generator, greek):
             lemma = lemma_list[0]
             lemma_pos_str = lemma_list[1]
             lemma_pos_list = lemma_pos_str.split(') (')
+            if not lemma.startswith("a)bare"):
+                continue
 
+            print()
+            print("lemma {}".format(lemma))
             for lemma_pos in lemma_pos_list:
                 # rm initial paren
                 if lemma_pos.startswith('('):
@@ -75,6 +80,9 @@ def parse_perseus_lemmata_file(file_generator, greek):
                     headword = replacer.beta_code(headword.upper() + ' ')[:-1].lower()  # add space to get final sigma 'ς', then rm it
 
                 #print(lemma, headword)
+                print("{lemma} {lemma!a} -> {headword} {headword!a}".format(lemma=lemma, headword=headword))
+                for c in lemma:
+                    print(unicodedata.name(c))
 
                 yield lemma, headword
 
```

Running `python3 transform_lemmata.py` shows the problem occurring with `a)barei=`:
```
lemma a)barei=
ἀβαρεῖ '\u1f00\u03b2\u03b1\u03c1\u03b5\u1fd6' -> ἀβαρής '\u1f00\u03b2\u03b1\u03c1\u03ae\u03c2'
GREEK SMALL LETTER ALPHA WITH PSILI
GREEK SMALL LETTER BETA
GREEK SMALL LETTER ALPHA
GREEK SMALL LETTER RHO
GREEK SMALL LETTER EPSILON
GREEK SMALL LETTER IOTA WITH PERISPOMENI
ἀβαρεῖ '\u1f00\u03b2\u03b1\u03c1\u03b5\u03b9\u0342' -> ἀβαρής '\u1f00\u03b2\u03b1\u03c1\u03ae\u03c2'
GREEK SMALL LETTER ALPHA WITH PSILI
GREEK SMALL LETTER BETA
GREEK SMALL LETTER ALPHA
GREEK SMALL LETTER RHO
GREEK SMALL LETTER EPSILON
GREEK SMALL LETTER IOTA
COMBINING GREEK PERISPOMENI
```

In the first iteration of the `lemma_pos_list`, the function yields
```
lemma == '\u1f00\u03b2\u03b1\u03c1\u03b5\u1fd6'
```
In the second iteration, the precomposed `'\u1fd6'` has become `'\u03b9\u0342'`, resulting in a different key. I'm not sure why `'\u1f00'` was not similarly affected.
```
lemma == '\u1f00\u03b2\u03b1\u03c1\u03b5\u03b9\u0342'
```
And in the output greek_lemmata_cltk.py, there are what are apparently duplicate entries for ἀβαρεῖ; however they actually differ in normalization. The same phenomenon affects ἀβαρεῖς.
```
'ἀβαρεῖ': 'ἀβαρής',
'ἀβαρεῖ': 'ἀβαρής',
```

This is somewhat related to #4 in that entries in `LEMMATA` should have uniform normalization.

**Comment by kylepjohnson** [comment]
Hey @whoopsedesy thank you for all of this.

I did these files a long time ago, before we had the ``cltk_normalize()`` function [http://docs.cltk.org/en/latest/greek.html#normalization] and, frankly, wasn't as careful as I should have been.

Anything PRs that don't affect the core project, I'll accept quickly. If they do touch on core dependencies, the team may be slow for review.
