### ISSUE TITLE
Lemmata ending in numerals

### ISSUE THREAD

**Issue by whoopsedesy** [cltk/greek_lexica_perseus#9]
Various lemmata in greek-lemmata.txt end in a numeral, which seems to be an error.
```
$ awk '$1 ~ /[0123456789]$/ {print $1}' greek-lemmata.txt
a(/lios1
a(li/zw1
a(li/zw2
a(mo/s1
a(mo/s2
a)/gxouros2
a)/n1
a)/n2
a)/nodos1
a)/nodos2
... 807 more ...
```

`s1`, `s2`, and `s3` are beta codes, but I don't think that's what's going on here. `s1` stands for a medial sigma and `s2` stands for a terminal sigma, but both `a(mo/s1` and `a(mo/s2` appear. These numerals make their way into the output `LEMMATA` dictionary, for example:
```
'αὔει': 'αὔω1',
'αὖ': 'αὖ2',
'δάιοισιν': 'δαίω1',
'δέαι': 'δέω1',
'δέδαιντο': 'δαίω2',
'διάιδοντα': 'διαείδω2',
'διάπανον': 'διά,ἀπόἄνω1',
'διάσωσιν': 'διάἄω3',
'διέκλεισαν': 'διάκλήιζω1',
'διέπεσαν': 'διάἔπειμι1',
... 7112 more ...
```

Ought these numerals to be stripped before processing? Or should they be stripped after retrieving them from the `LEMMATA` dictionary?

**Comment by kylepjohnson** [comment]
These come from the original Perseus data sets … they are keyed to their version of the LSJ … right? Honestly, it's been years since I thought of this. There might be reasons for keeping them, if we want to use it for dict lookup. However if not, then you're right.

BTW take a look at our experimental repo, where we have neural nets giving lemmas, too: https://github.com/cltk/cltkv1/ .

**Comment by sasansom** [comment]
Agreed, the numerals indicate different lemmata in the Perseus data set based on the LSJ entry. Take a(mo/s1 and a(mos2 from the list above: these are two distinct [lemmata](http://www.perseus.tufts.edu/hopper/resolveform?type=exact&lookup=a%28mo%2Fs&lang=greek); the first means 'h(me/teros' (our), the second 'tis' (someone). Cf. the LSJ at the TLG which uses (A), (B), etc. to mark the difference.

**Comment by kylepjohnson** [comment]
Thanks for confirming my memory. There are arguments either way, transforming them or not.

> Ought these numerals to be stripped before processing? Or should they be stripped after retrieving them from the LEMMATA dictionary?

To create a word list, then you need the numerals. But to merely reduce your vocabulary (say for classification using machine learning) then the numbers don't hurt.

~~@sasansom~~ @whoopsedesy what is the goal of your current work? If you have strong opinions don't hold back. Let me know … others in the project might be able to help you better.

**Comment by whoopsedesy** [comment]
Thanks for the reply. The numeric suffixes work fine for me -- I only need them to be distinct tokens representing distinct lemmata (i.e., it could just as well be a hash code or something). For use cases that need to recover the actual word underlying the lemma, it might be nice to have some distinct delimiter that avoids confusion with beta codes that end in a numeral, for example `a(mo/s!1` and `a(mo/s!2`.
